/**
 * The retrieval mechanism, laid bare — not the chat.
 *
 * Chat asks a question and gets prose back, generated by a model that read some passages.
 * This asks the same corpus the same hybrid search and shows exactly what came back and
 * why: rank, lexical score, dense score, rerank score, nothing written on top of it. The
 * two exist side by side because they answer different questions — "what should I do" is
 * Chat's, and "why did this passage rank first" is this screen's, and no amount of prose
 * generation ever answers the second one.
 */

import { useCallback, useRef, useState } from "react";

import { ApiError, search, type SearchHit } from "../api/client";
import type { Citation } from "../api/stream";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ProgressBar } from "./ProgressBar";

interface Props {
  token: string;
  onCitation: (citation: Citation) => void;
  searchable: boolean;
  labels?: string[];
}

type State =
  | { phase: "idle" }
  | { phase: "loading"; query: string }
  | { phase: "done"; query: string; hits: SearchHit[]; degraded: boolean; reason: string | null; tookMs: number }
  | { phase: "error"; query: string; message: string };

export function Search({ token, onCitation, searchable, labels }: Props) {
  const [state, setState] = useState<State>({ phase: "idle" });
  const [query, setQuery] = useState("");
  const inflight = useRef<AbortController | null>(null);

  const run = useCallback(
    async (q: string) => {
      inflight.current?.abort();
      const controller = new AbortController();
      inflight.current = controller;

      setState({ phase: "loading", query: q });
      try {
        const result = await search(token, q, labels, controller.signal);
        setState({
          phase: "done",
          query: q,
          hits: result.hits,
          degraded: result.degraded,
          reason: result.reason,
          tookMs: result.took_ms,
        });
      } catch (error) {
        // An abort is the user cancelling, not a failure — `cancel` below already put the
        // state back to idle, and overwriting that with an error would fight it.
        if (controller.signal.aborted) return;
        setState({
          phase: "error",
          query: q,
          message: error instanceof ApiError ? error.message : "The search failed.",
        });
      }
    },
    [token, labels],
  );

  const cancel = useCallback(() => {
    inflight.current?.abort();
    setState({ phase: "idle" });
  }, []);

  if (!searchable) {
    return (
      <p className="rounded-xl border border-border bg-card p-4 text-sm text-muted-foreground">
        There are no documents to search yet. Upload one to get started.
      </p>
    );
  }

  const busy = state.phase === "loading";

  return (
    <section className="max-w-3xl space-y-4">
      <form
        onSubmit={(event) => {
          event.preventDefault();
          const asked = query.trim();
          if (asked) void run(asked);
        }}
        className="flex gap-2"
      >
        <Input
          value={query}
          onChange={(event) => setQuery(event.target.value)}
          placeholder="Search passages by keyword and meaning"
          aria-label="Search"
          maxLength={1000}
          className="h-11 flex-1 border-border bg-card text-foreground placeholder:text-muted-foreground focus-visible:border-primary focus-visible:ring-primary/40"
        />
        <Button
          type="submit"
          disabled={busy || !query.trim()}
          aria-pressed={busy}
          className={`h-11 text-white transition-all ${
            busy
              ? "translate-y-px bg-primary/80 shadow-inner disabled:opacity-100"
              : "bg-primary hover:bg-primary/90 disabled:opacity-50"
          }`}
        >
          {busy ? "Searching…" : "Search"}
        </Button>
        {busy && (
          <Button
            type="button"
            variant="ghost"
            onClick={cancel}
            className="h-11 text-muted-foreground hover:text-foreground"
          >
            Cancel
          </Button>
        )}
      </form>

      {state.phase === "loading" && (
        <ProgressBar key={state.query} label="Ranking passages" />
      )}

      {state.phase === "error" && (
        <p role="alert" className="rounded-lg border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive">
          {state.message}
        </p>
      )}

      {state.phase === "done" && (
        <div className="space-y-3">
          <p className="text-xs text-muted-foreground">
            {state.hits.length} passage{state.hits.length === 1 ? "" : "s"} · {state.tookMs} ms
            {state.degraded && (
              <span className="ml-2 text-zenith-amber">Degraded: {state.reason}</span>
            )}
          </p>

          {state.hits.length === 0 && (
            <div className="rounded-lg border border-dashed border-border p-10 text-center text-sm text-muted-foreground">
              Nothing matched that query.
            </div>
          )}

          <ul className="divide-y divide-border overflow-hidden rounded-lg border border-border">
            {state.hits.map((hit, index) => (
              <li key={hit.chunk_id}>
                <button
                  type="button"
                  onClick={() =>
                    onCitation({
                      marker: index + 1,
                      chunk_id: hit.chunk_id,
                      document_id: hit.document_id,
                      filename: hit.filename,
                      page_num: hit.page_num,
                      text: hit.text,
                      bboxes: hit.bboxes,
                    })
                  }
                  className="w-full px-4 py-3.5 text-left transition-colors hover:bg-secondary/40"
                >
                  <div className="flex items-baseline justify-between gap-4">
                    <p className="truncate text-sm font-medium text-foreground">
                      {hit.filename} <span className="text-muted-foreground">· page {hit.page_num}</span>
                    </p>
                    <span className="shrink-0 font-mono text-xs text-muted-foreground">
                      #{index + 1}
                    </span>
                  </div>
                  <p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{hit.text}</p>
                  <p className="mt-2 flex flex-wrap gap-x-3 font-mono text-xs text-muted-foreground/80">
                    {hit.lexical_rank !== null && (
                      <span>lexical #{hit.lexical_rank} ({hit.lexical_score?.toFixed(3)})</span>
                    )}
                    {hit.dense_rank !== null && (
                      <span>dense #{hit.dense_rank} ({hit.dense_score?.toFixed(3)})</span>
                    )}
                    {hit.rerank_score !== null && <span>rerank {hit.rerank_score.toFixed(3)}</span>}
                    <span>rrf {hit.score.toFixed(4)}</span>
                  </p>
                </button>
              </li>
            ))}
          </ul>
        </div>
      )}
    </section>
  );
}
