/**
 * The retrieval mechanism, laid bare — not the chat.
 *
 * Chat asks a question and gets prose back, generated by a model that read some passages.
 * This asks the same corpus the same hybrid search and shows exactly what came back and
 * why: rank, lexical score, dense score, rerank score, nothing written on top of it. The
 * two exist side by side because they answer different questions — "what should I do" is
 * Chat's, and "why did this passage rank first" is this screen's, and no amount of prose
 * generation ever answers the second one.
 */

import { useCallback, useEffect, useRef, useState } from "react";

import { search, type SearchHit } from "./api";
import { ApiError } from "@/shared/api/http";
import type { Citation } from "@/features/chat";
import { Clock, Search as SearchIcon } from "lucide-react";

import { TagChips, labels as fetchLabels } from "@/features/labels";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ProgressBar } from "@/shared/components/ProgressBar";

interface Props {
  token: string;
  onCitation: (citation: Citation) => void;
  searchable: boolean;
  labels?: string[];
  /** Clicking a chip on a result narrows the workspace to that label. */
  onSelectTag?: (name: string) => void;
}

type State =
  | { phase: "idle" }
  | { phase: "loading"; query: string }
  | { phase: "done"; query: string; hits: SearchHit[]; degraded: boolean; reason: string | null; tookMs: number }
  | { phase: "error"; query: string; message: string };

/** Starting points for a corpus nobody has searched yet — a blank box gives no clue what
    is even in there. Deliberately generic so they stay sensible whatever was uploaded, and
    shown only until there is real history to offer instead. */
const SUGGESTIONS = ["obligations", "deadlines", "definitions", "penalties"];

const RECENT_KEY = "zenith.recent-searches";
const RECENT_LIMIT = 5;

/**
 * Recent searches live in the browser, not on the server, and that is a decision rather
 * than a shortcut.
 *
 * `GET /query/history` exists and would have been the obvious source — but it records
 * *questions asked in Chat*. Search is deliberately not written to it: it runs retrieval
 * alone, generates nothing, and nobody has decided it should be part of the tenant's
 * audited record. Reading chat history here would put a different kind of thing under a
 * heading that says "recent searches", which is worse than having no list.
 *
 * The trade-off is honest and worth stating: this is per-browser and per-device. If these
 * should follow a person between machines — or be visible to an auditor — that is a
 * server-side feature and a separate decision about what Search owes the record.
 */
function readRecent(): string[] {
  try {
    const raw: unknown = JSON.parse(localStorage.getItem(RECENT_KEY) ?? "[]");
    return Array.isArray(raw) ? raw.filter((item): item is string => typeof item === "string") : [];
  } catch {
    // Hand-edited or written by an older version. A broken preference is not worth an
    // error on a screen whose job is to search.
    return [];
  }
}

function remember(query: string): string[] {
  // Most recent first, no duplicates: searching the same thing twice should move it to the
  // top rather than fill the list with one word.
  const next = [query, ...readRecent().filter((item) => item !== query)].slice(0, RECENT_LIMIT);
  localStorage.setItem(RECENT_KEY, JSON.stringify(next));
  return next;
}

export function Search({ token, onCitation, searchable, labels, onSelectTag }: Props) {
  // Resolved from what this caller reaches; an unknown id belongs to a label they see the
  // passage through some other route, and is not theirs to learn the name of.
  const [known, setKnown] = useState<Map<string, string>>(new Map());
  const [state, setState] = useState<State>({ phase: "idle" });
  const [query, setQuery] = useState("");
  const [recent, setRecent] = useState<string[]>(readRecent);
  const inflight = useRef<AbortController | null>(null);

  useEffect(() => {
    let cancelled = false;
    void fetchLabels(token)
      .then((all) => !cancelled && setKnown(new Map(all.map((l) => [l.id, l.name]))))
      .catch(() => !cancelled && setKnown(new Map()));
    return () => {
      cancelled = true;
    };
  }, [token]);

  const namesFor = useCallback(
    (hit: SearchHit): string[] =>
      hit.label_ids
        .map((id) => known.get(id))
        .filter((name): name is string => name !== undefined)
        .sort(),
    [known],
  );

  const run = useCallback(
    async (q: string) => {
      inflight.current?.abort();
      const controller = new AbortController();
      inflight.current = controller;

      setState({ phase: "loading", query: q });
      try {
        const result = await search(token, q, labels, controller.signal);
        // Recorded once the search came back, not when it was submitted: a query that
        // errored or was cancelled is not one worth offering again.
        setRecent(remember(q));
        setState({
          phase: "done",
          query: q,
          hits: result.hits,
          degraded: result.degraded,
          reason: result.reason,
          tookMs: result.took_ms,
        });
      } catch (error) {
        // An abort is the user cancelling, not a failure — `cancel` below already put the
        // state back to idle, and overwriting that with an error would fight it.
        if (controller.signal.aborted) return;
        setState({
          phase: "error",
          query: q,
          message: error instanceof ApiError ? error.message : "The search failed.",
        });
      }
    },
    [token, labels],
  );

  const cancel = useCallback(() => {
    inflight.current?.abort();
    setState({ phase: "idle" });
  }, []);

  if (!searchable) {
    return (
      <p className="rounded-xl border border-border bg-card p-4 text-sm text-muted-foreground">
        There are no documents to search yet. Upload one to get started.
      </p>
    );
  }

  const busy = state.phase === "loading";

  return (
    <section className="space-y-4">
      {/* One rounded field with the control inside it, rather than an input sitting next to
          a button. The pill is the shape a search box has everywhere the people using this
          already search, and putting the submit inside the same border makes it read as one
          object instead of two that happen to be adjacent. */}
      <form
        onSubmit={(event) => {
          event.preventDefault();
          const asked = query.trim();
          if (asked) void run(asked);
        }}
      >
        <div className="flex items-center gap-2 rounded-full border border-input bg-input/30 py-2 pr-2 pl-5 shadow-sm transition-colors focus-within:border-primary/50">
          <SearchIcon className="size-4 shrink-0 text-muted-foreground" />
          <Input
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Search passages by keyword and meaning"
            aria-label="Search"
            maxLength={1000}
            // `dark:bg-transparent` is load-bearing: the base `Input` carries
            // `dark:bg-input/30`, which outlives a plain `bg-transparent` in the dark theme
            // and painted the field a shade off the pill around it — two surfaces where
            // there should be one.
            className="h-8 flex-1 border-0 bg-transparent p-0 text-base text-foreground shadow-none placeholder:text-muted-foreground focus-visible:ring-0 dark:bg-transparent"
          />
          {busy ? (
            <Button
              type="button"
              onClick={cancel}
              className="h-9 shrink-0 rounded-full bg-foreground px-4 text-sm text-background hover:bg-foreground/90"
            >
              Stop
            </Button>
          ) : (
            <Button
              type="submit"
              disabled={!query.trim()}
              className="h-9 shrink-0 rounded-full bg-primary px-5 text-sm text-white hover:bg-primary/90 disabled:opacity-40"
            >
              Search
            </Button>
          )}
        </div>
      </form>

      {/* The screen used to be a lone input on an empty panel — nothing said what this
          searches, how it differs from Chat, or what to type. It is the landing screen, so
          it is the one place worth spending a few lines explaining the mechanism. */}
      {state.phase === "idle" && (
        <div className="space-y-5 py-10 text-center">
          <div className="mx-auto flex size-12 items-center justify-center rounded-full border border-input bg-secondary">
            <SearchIcon className="size-5 text-primary" />
          </div>
          <div className="space-y-1.5">
            <p className="text-base font-medium text-foreground">Search your corpus</p>
            <p className="mx-auto max-w-md text-sm text-muted-foreground">
              Keyword and meaning at once — passages come back ranked, with the page they
              came from. Nothing is generated here; use Chat for a written answer.
            </p>
          </div>
          <div className="space-y-2">
            <p className="text-xs tracking-wide text-muted-foreground/70 uppercase">
              {recent.length > 0 ? "Recent" : "Try"}
            </p>
            <div className="flex flex-wrap justify-center gap-2">
              {(recent.length > 0 ? recent : SUGGESTIONS).map((suggestion) => (
                <button
                  key={suggestion}
                  type="button"
                  onClick={() => {
                    setQuery(suggestion);
                    void run(suggestion);
                  }}
                  className="inline-flex max-w-xs items-center gap-1.5 rounded-full border border-input bg-card px-3.5 py-1.5 text-xs text-muted-foreground transition-colors hover:border-primary/50 hover:text-foreground"
                >
                  {recent.length > 0 && <Clock className="size-3 shrink-0 opacity-60" />}
                  <span className="truncate">{suggestion}</span>
                </button>
              ))}
            </div>
            {recent.length > 0 && (
              <button
                type="button"
                onClick={() => {
                  localStorage.removeItem(RECENT_KEY);
                  setRecent([]);
                }}
                className="text-xs text-muted-foreground/60 transition-colors hover:text-foreground"
              >
                Clear
              </button>
            )}
          </div>
        </div>
      )}

      {state.phase === "loading" && (
        <ProgressBar key={state.query} label="Ranking passages" />
      )}

      {state.phase === "error" && (
        <p role="alert" className="rounded-lg border border-destructive/40 bg-destructive/10 p-4 text-sm text-destructive">
          {state.message}
        </p>
      )}

      {state.phase === "done" && (
        <div className="space-y-3">
          <p className="text-xs text-muted-foreground">
            {state.hits.length} passage{state.hits.length === 1 ? "" : "s"} · {state.tookMs} ms
            {state.degraded && (
              <span className="ml-2 text-zenith-amber">Degraded: {state.reason}</span>
            )}
          </p>

          {state.hits.length === 0 && (
            <div className="rounded-lg border border-dashed border-border p-10 text-center text-sm text-muted-foreground">
              Nothing matched that query.
            </div>
          )}

          {/* Separate cards, same as the history and document lists. A hit is a filename,
              two lines of the passage and a row of scores — running text, where a hairline
              rule gives the eye nothing to tell it where one result stops and the next
              starts. */}
          <ul className="space-y-2">
            {state.hits.map((hit, index) => (
              <li key={hit.chunk_id}>
                <button
                  type="button"
                  onClick={() =>
                    onCitation({
                      marker: index + 1,
                      chunk_id: hit.chunk_id,
                      document_id: hit.document_id,
                      filename: hit.filename,
                      page_num: hit.page_num,
                      text: hit.text,
                      bboxes: hit.bboxes,
                    })
                  }
                  className="w-full rounded-lg border border-border bg-secondary px-4 py-3.5 text-left transition-colors hover:bg-secondary/70"
                >
                  <div className="flex items-baseline justify-between gap-4">
                    <p className="truncate text-sm font-medium text-foreground">
                      {hit.filename} <span className="text-muted-foreground">· page {hit.page_num}</span>
                    </p>
                    <span className="shrink-0 font-mono text-xs text-muted-foreground">
                      #{index + 1}
                    </span>
                  </div>
                  <p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{hit.text}</p>
                  {/* What this passage is filed under, on the result itself — otherwise
                      the only way to know is to open the document and look. */}
                  <div className="mt-2 flex flex-wrap gap-1.5">
                    <TagChips names={namesFor(hit)} onSelect={onSelectTag} short />
                  </div>
                  <p className="mt-2 flex flex-wrap gap-x-3 font-mono text-xs text-muted-foreground/80">
                    {hit.lexical_rank !== null && (
                      <span>lexical #{hit.lexical_rank} ({hit.lexical_score?.toFixed(3)})</span>
                    )}
                    {hit.dense_rank !== null && (
                      <span>dense #{hit.dense_rank} ({hit.dense_score?.toFixed(3)})</span>
                    )}
                    {hit.rerank_score !== null && <span>rerank {hit.rerank_score.toFixed(3)}</span>}
                    <span>rrf {hit.score.toFixed(4)}</span>
                  </p>
                </button>
              </li>
            ))}
          </ul>
        </div>
      )}
    </section>
  );
}
