"""initial schema

Revision ID: 4c0ed1084bf1
Revises:
Create Date: 2026-08-01 12:08:57.496226

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_search")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_spaces",
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('building', 'active', 'retired')",
            name=op.f("ck_embedding_spaces_status_valido"),
        ),
        sa.PrimaryKeyConstraint("model", "version", name=op.f("pk_embedding_spaces")),
    )
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_permissions")),
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("name", name=op.f("uq_tenants_name")),
    )
    op.create_table(
        "access_labels",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_access_labels_tenant_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_labels")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_access_labels_tenant_id_name")),
    )
    op.create_table(
        "llm_config",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("endpoint_url", sa.String(), nullable=False),
        sa.Column("api_key_encrypted", sa.String(), nullable=True),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("certified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("certification_result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_llm_config_tenant_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("tenant_id", name=op.f("pk_llm_config")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("is_system", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_roles_tenant_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_roles_tenant_id_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("token_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_users_tenant_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("tenant_id", "email", name=op.f("uq_users_tenant_id_email")),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="pending", nullable=False),
        sa.Column("status_detail", sa.String(), nullable=True),
        sa.Column("label_ids", postgresql.ARRAY(sa.UUID()), server_default="{}", nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'parsing', 'chunking', 'embedding', 'ready', 'failed')",
            name=op.f("ck_documents_status_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_documents_tenant_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_documents_uploaded_by"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("tenant_id", "sha256", name=op.f("uq_documents_tenant_id_sha256")),
    )
    op.create_index(
        "ix_documents_label_ids", "documents", ["label_ids"], unique=False, postgresql_using="gin"
    )
    op.create_table(
        "queries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("answer", sa.String(), nullable=True),
        sa.Column("model_used", sa.String(), nullable=True),
        sa.Column("latency_retrieval_ms", sa.Integer(), nullable=True),
        sa.Column("latency_generation_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_queries_tenant_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_queries_user_id"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_queries")),
    )
    op.create_table(
        "role_labels",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("label_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["access_labels.id"],
            name=op.f("fk_role_labels_label_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_role_labels_role_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("role_id", "label_id", name=op.f("pk_role_labels")),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_code"],
            ["permissions.code"],
            name=op.f("fk_role_permissions_permission_code"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_role_permissions_role_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_code", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("label_ids", postgresql.ARRAY(sa.UUID()), server_default="{}", nullable=False),
        sa.Column("page_num", sa.Integer(), nullable=False),
        sa.Column("char_start", sa.Integer(), nullable=False),
        sa.Column("char_end", sa.Integer(), nullable=False),
        sa.Column(
            "bboxes", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("section", sa.String(), nullable=True),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("context_prefix", sa.String(), nullable=True),
        sa.Column("chunking_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', text)", persisted=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_chunks_document_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_chunks_tenant_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chunks")),
    )
    op.create_index(
        "ix_chunks_label_ids", "chunks", ["label_ids"], unique=False, postgresql_using="gin"
    )
    op.create_index("ix_chunks_tenant_id", "chunks", ["tenant_id"], unique=False)
    op.create_index("ix_chunks_tsv", "chunks", ["tsv"], unique=False, postgresql_using="gin")
    op.create_table(
        "document_labels",
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("label_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_labels_document_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["access_labels.id"],
            name=op.f("fk_document_labels_label_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("document_id", "label_id", name=op.f("pk_document_labels")),
    )
    op.create_table(
        "pages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("page_num", sa.Integer(), nullable=False),
        sa.Column("extraction_method", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_pages_document_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pages")),
        sa.UniqueConstraint("document_id", "page_num", name=op.f("uq_pages_document_id_page_num")),
    )
    op.create_table(
        "chunk_embeddings",
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("embedding_model", sa.String(), nullable=False),
        sa.Column("embedding_version", sa.String(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
            name=op.f("fk_chunk_embeddings_chunk_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_chunk_embeddings_tenant_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "chunk_id", "embedding_model", "embedding_version", name=op.f("pk_chunk_embeddings")
        ),
    )
    op.create_table(
        "query_citations",
        sa.Column("query_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.UUID(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score_bm25", sa.Float(), nullable=True),
        sa.Column("score_vector", sa.Float(), nullable=True),
        sa.Column("score_rrf", sa.Float(), nullable=True),
        sa.Column("score_rerank", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
            name=op.f("fk_query_citations_chunk_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["queries.id"],
            name=op.f("fk_query_citations_query_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("query_id", "chunk_id", name=op.f("pk_query_citations")),
    )
    # ### end Alembic commands ###

    _create_hnsw_index()
    _create_context_functions()
    _enable_rls()
    _create_application_role()


def _create_hnsw_index() -> None:
    """Vector index. `vector_cosine_ops` because BGE-M3 returns normalised vectors."""
    op.create_index(
        "ix_chunk_embeddings_hnsw",
        "chunk_embeddings",
        ["embedding"],
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 16, "ef_construction": 64},
    )


def _create_context_functions() -> None:
    """Readers for the RLS context.

    `STABLE` so the planner evaluates them once per query rather than once per row.
    With no context set they return NULL and an empty set, so no policy is ever
    satisfied: the failure is closed.
    """
    op.execute(
        """
        CREATE FUNCTION zenith_current_tenant() RETURNS uuid
        LANGUAGE sql STABLE AS $$
            SELECT nullif(current_setting('zenith.tenant_id', true), '')::uuid
        $$
        """
    )
    op.execute(
        """
        CREATE FUNCTION zenith_current_labels() RETURNS uuid[]
        LANGUAGE sql STABLE AS $$
            SELECT coalesce(
                string_to_array(nullif(current_setting('zenith.label_ids', true), ''), ',')::uuid[],
                '{}'::uuid[]
            )
        $$
        """
    )


# Level 1: the row carries its own `tenant_id`.
TENANT_POLICIES = {
    "tenants": "id = zenith_current_tenant()",
    "users": "tenant_id = zenith_current_tenant()",
    "roles": "tenant_id = zenith_current_tenant()",
    "access_labels": "tenant_id = zenith_current_tenant()",
    "queries": "tenant_id = zenith_current_tenant()",
    "llm_config": "tenant_id = zenith_current_tenant()",
    "chunk_embeddings": "tenant_id = zenith_current_tenant()",
}

# Level 2: the label, on top of the tenant. A document with no labels is visible to
# the whole tenant; with labels, only if the role reaches at least one.
LABEL_POLICIES = {
    "documents": (
        "tenant_id = zenith_current_tenant() AND "
        "(label_ids = '{}'::uuid[] OR label_ids && zenith_current_labels())"
    ),
    "chunks": (
        "tenant_id = zenith_current_tenant() AND "
        "(label_ids = '{}'::uuid[] OR label_ids && zenith_current_labels())"
    ),
}

# Derived: they inherit the parent's visibility. The EXISTS applies the parent's own
# policy in turn, so the rule never has to be spelled out in two places.
DERIVED_POLICIES = {
    "pages": "EXISTS (SELECT 1 FROM documents d WHERE d.id = pages.document_id)",
    "document_labels": (
        "EXISTS (SELECT 1 FROM documents d WHERE d.id = document_labels.document_id)"
    ),
    "role_permissions": "EXISTS (SELECT 1 FROM roles r WHERE r.id = role_permissions.role_id)",
    "role_labels": "EXISTS (SELECT 1 FROM roles r WHERE r.id = role_labels.role_id)",
    "user_roles": "EXISTS (SELECT 1 FROM users u WHERE u.id = user_roles.user_id)",
    "query_citations": "EXISTS (SELECT 1 FROM queries q WHERE q.id = query_citations.query_id)",
}

# Global catalogues, no customer data: `permissions` is defined by the software and
# `embedding_spaces` describes models, not content.
TABLES_WITHOUT_RLS = ("permissions", "embedding_spaces")

TABLES_WITH_RLS = (*TENANT_POLICIES, *LABEL_POLICIES, *DERIVED_POLICIES)


def _enable_rls() -> None:
    for table, condition in {
        **TENANT_POLICIES,
        **LABEL_POLICIES,
        **DERIVED_POLICIES,
    }.items():
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_isolation ON {table} "
            f"USING ({condition}) WITH CHECK ({condition})"
        )


def _create_application_role() -> None:
    """Role the application connects as.

    It does not own the tables, which is why the policies apply to it. FORCE ROW
    LEVEL SECURITY is deliberately not used: the owner `zenith` must be able to
    create the first tenant from the CLI, when no context exists yet.

    The risk that opens is real and is covered by `core.database.verify_rls_active`:
    if someone points the application at the owner credentials, RLS would be inactive
    with no symptom at all. That is why startup checks it and refuses to serve.
    """
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'zenith_app') THEN
                CREATE ROLE zenith_app NOLOGIN;
            END IF;
        END
        $$
        """
    )
    op.execute("GRANT USAGE ON SCHEMA public TO zenith_app")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO zenith_app")
    op.execute("GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO zenith_app")


def downgrade() -> None:
    for table in TABLES_WITH_RLS:
        op.execute(f"DROP POLICY IF EXISTS {table}_isolation ON {table}")
        op.execute(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY")
    op.execute("DROP INDEX IF EXISTS ix_chunk_embeddings_hnsw")
    op.execute("DROP FUNCTION IF EXISTS zenith_current_labels()")
    op.execute("DROP FUNCTION IF EXISTS zenith_current_tenant()")
    _revoke_application_role()
    _drop_tables()


def _revoke_application_role() -> None:
    op.execute("REVOKE ALL ON ALL TABLES IN SCHEMA public FROM zenith_app")
    op.execute("REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM zenith_app")
    op.execute("REVOKE USAGE ON SCHEMA public FROM zenith_app")


def _drop_tables() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("query_citations")
    op.drop_table("chunk_embeddings")
    op.drop_table("pages")
    op.drop_table("document_labels")
    op.drop_index("ix_chunks_tsv", table_name="chunks", postgresql_using="gin")
    op.drop_index("ix_chunks_tenant_id", table_name="chunks")
    op.drop_index("ix_chunks_label_ids", table_name="chunks", postgresql_using="gin")
    op.drop_table("chunks")
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_table("role_labels")
    op.drop_table("queries")
    op.drop_index("ix_documents_label_ids", table_name="documents", postgresql_using="gin")
    op.drop_table("documents")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("llm_config")
    op.drop_table("access_labels")
    op.drop_table("tenants")
    op.drop_table("permissions")
    op.drop_table("embedding_spaces")
    # ### end Alembic commands ###
